apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-demo-app
  namespace: default
  labels:
    app: eks-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-demo-app
  template:
    metadata:
      labels:
        app: eks-demo-app
    spec:
      containers:
        - name: eks-demo-app
          image: 854469103070.dkr.ecr.us-east-1.amazonaws.com/eks-demo-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: eks-demo-app
  namespace: default
spec:
  selector:
    app: eks-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eks-demo-app
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-05ed576035a0d60db, subnet-0b2716f9690ba195d
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eks-demo-app
                port:
                  number: 80